#pragma once

#define WINDOW_WIDTH 1920.f
#define WINDOW_HEIGHT 1080.f

#define BRICK_COL 20
#define BRICK_ROW 10

#define BRICK_OUTLINE 2.f
#define BRICK_WIDTH WINDOW_WIDTH/(float)BRICK_COL - BRICK_OUTLINE
#define BRICK_HEIGHT 50 - BRICK_OUTLINE